### PR TITLE
Native b58 implementation

### PR DESCRIPTION
**Pull request by peerchemist**

### CODE REVIEW

**Comment by peerchemist** [comment]
All unittests are passing.

**Comment by SimoneBronzini** [comment]
Thanks for your PR! The code looks fine, however I believe we should have more thorough testing, base58 being a very important core part of the system. Some base58 test vectors can be found at the following links:
* [Bitcoin Core vectors](https://github.com/bitcoin/bitcoin/blob/master/src/test/data/base58_encode_decode.json) (these strings apparently need to be `unhexlify`ed before encoding and `hexlify`ed after decoding to be compared)
* [Base58 go library](https://github.com/runeaune/bitcoin-base58/blob/master/base58_test.go) (some conversions needed as above)
* [These](https://github.com/bitcoin/bitcoin/blob/master/src/test/data/base58_keys_valid.json) Bitcoin Core test vectors might be another good source of inspiration

One more thing: I see the test class is called `P2THTest` and the same is printed at test `setUpClass`. I guess that is the wrong name for these tests.

**Comment by peerchemist** [comment]
We've been using this b58 implementation for well over a year in the pypeerassets project. I've simply copied the code over and implemented a test in unittest (we use pytest here).

**Comment by peerchemist** [comment]
Expanded the unittest.

**Pull request merged**
