### PR TITLE
document and annotate TxIn

### PR DESCRIPTION
**Pull request by peerchemist**

### CODE REVIEW

**Comment by SimoneBronzini** [comment]
Thanks for your contribution! I'm not really into type annotations in Python. However, docstrings are highly appreciated!

**Comment by peerchemist** [comment]
Annotations help to understand the code easier, and if you use mypy they help to detect bugs and errors early on.

**Comment by peerchemist** [comment]
Hello,

will you merge this?

**Comment by SimoneBronzini** [comment]
Hi, sorry for the delay, I am quite busy in these days, I will merge as soon as possible.

**Pull request merged**
