### PR TITLE
PrivateKey: simplify WIF decoding

### PR DESCRIPTION
**Pull request by peerchemist**
Simplification of WIF decoding code.

### CODE REVIEW

**Comment by SimoneBronzini** [comment]
That's a very good idea! However, I would like to add the notion of compressed/uncompressed pubkeys inside `PrivateKey`, to be used in case of `pub()`, so I am already in the process of refactoring that part.

**Comment by peerchemist** [comment]
WIFs usually use compressed pubkey by default.

**Comment by peerchemist** [comment]
@SimoneBronzini I think we should add `to_wif` method on PrivateKey class, to allow for exporting to WIF format. `from_wif` can be made to save wif prefix by setattr to PrivateKey - which can then be used to assemble it back to WIF.

**Comment by peerchemist** [comment]
Like here: https://github.com/PeerAssets/pypeerassets/blob/master/pypeerassets/kutil.py#L73

**Comment by SimoneBronzini** [comment]
I completely agree, will work on this as soon as possible.

**Pull request closed without merging**
